version: '3'

services:
  hxbuild:
    build: .
    command: /bin/bash
    tty: true
    volumes:
      - .:/code
    working_dir: /code
    expose:
      - "8090"
      - "8091"
      - "9034"
#    ports:
#      - "8090:8090"
#      - "8091:8091"
#      - "9034:9034"
